### ISSUE TITLE
Collect and store real estate listing data.

### ISSUE THREAD

**Issue by czhaoca** [thekimsplustwo/VanCityPropertyPulse#1]
Including:

- [x] #31
- [ ] Document API.
- [x] Test API in local environment.
- [x] Set up a MongoDB database for storing listing data.
- [ ] Use Node.js and Express.js to scrape or consume data from a real estate API.
  - #295  
- [ ] Schedule regular data updates.
- [x] #6
- [ ] Fix requirements
